#
# https://help.github.com/en/actions/automating-your-workflow-with-github-actions
#

name: Release

on:
  push:
    tags:
      - v*

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    env:
      GO111MODULE: on
      CLOUDSDK_CORE_PROJECT: ${{ secrets.CLOUDSDK_CORE_PROJECT }}
    steps:
      # https://github.com/actions/checkout
      - uses: actions/checkout@v2

      # https://github.com/actions/setup-ruby
      - uses: actions/setup-ruby@v1
        with:
          ruby-version: '2.7'

      - name: Check ruby version
        run: |
          set -x
          ruby -v
          gem -v
          gem env
          gem list

      # https://github.com/GoogleCloudPlatform/github-actions/tree/master/setup-gcloud
      - uses: GoogleCloudPlatform/github-actions/setup-gcloud@master
        with:
          version: '275.0.0'
          service_account_email: ${{ secrets.GCP_SA_EMAIL }}
          service_account_key: ${{ secrets.GCP_SA_KEY }}

      - name: Check Cloud SDK version/components
        run: |
          set -x
          gcloud version
          gcloud info
          gcloud components list
          gcloud auth list

      - name: Update and install Cloud SDK components
        run: |
          set -x
          gcloud components update
          gcloud components install app-engine-go
          gcloud components list

      - name: Stage application code to Cloud Storage
        run: ./deploy-tools/stage.sh $(basename ${{ github.ref }})

